version: '3.8'
services:
  web:
    build: .
    container_name: ci_pos
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    command: >
      bash -c "
      composer install &&
      chown -R www-data:www-data /var/www/html/writable &&
      chmod -R 775 /var/www/html/writable &&
      apache2-foreground
      "
    restart: always